
window.QUESTIONS = [
  { q: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Printing Unit', 'Control Process Unit'], answer: 0 },
  { q: 'Which is an operating system?', options: ['Python', 'Linux', 'HTML', 'SQL'], answer: 1 },
  { q: 'Shortcut for copy on Windows?', options: ['Ctrl + X', 'Ctrl + C', 'Ctrl + V', 'Ctrl + Z'], answer: 1 },
  { q: 'Primary memory is also called…', options: ['Cache', 'RAM', 'SSD', 'HDD'], answer: 1 },
  { q: 'Binary of decimal 2?', options: ['10', '11', '01', '00'], answer: 0 },
  { q: 'Which is a web browser?', options: ['Chrome', 'Linux', 'Apache', 'MySQL'], answer: 0 },
  { q: 'HTML is used for…', options: ['Styling', 'Structuring webpages', 'Database', 'Server scripting'], answer: 1 },
  { q: 'CSS stands for…', options: ['Creative Style System', 'Cascading Style Sheets', 'Computer Style Sheet', 'Code Style Sheet'], answer: 1 },
  { q: 'Device to input text?', options: ['Monitor', 'Keyboard', 'Printer', 'Speaker'], answer: 1 },
  { q: 'Which is not an input device?', options: ['Mouse', 'Scanner', 'Microphone', 'Projector'], answer: 3 },

  { q: 'JavaScript runs in…', options: ['Browser', 'Database', 'OS kernel', 'Router'], answer: 0 },
  { q: 'Which is a loop?', options: ['if', 'for', 'switch', 'case'], answer: 1 },
  { q: '== vs === in JS?', options: ['Both same', '=== checks type too', '== checks type too', 'Neither works'], answer: 1 },
  { q: 'Array index starts at…', options: ['1', '0', '2', 'Depends'], answer: 1 },
  { q: 'Which is not a language?', options: ['Python', 'C++', 'React', 'Java'], answer: 2 },
  { q: 'const variable can be…', options: ['Reassigned', 'Redeclared', 'Not reassigned', 'Type changes only'], answer: 2 },
  { q: 'Which prints to console?', options: ['print()', 'echo()', 'console.log()', 'println()'], answer: 2 },
  { q: 'JSON stands for…', options: ['Java Standard Object Notation', 'JavaScript Object Notation', 'Join Server Object Network', 'None'], answer: 1 },
  { q: 'HTTP status 404 means…', options: ['OK', 'Not Found', 'Server Error', 'Redirect'], answer: 1 },
  { q: 'Git command to copy repo?', options: ['git push', 'git pull', 'git clone', 'git init'], answer: 2 },

  { q: 'LAN stands for…', options: ['Local Area Network', 'Large Area Network', 'Line Area Net', 'Local Access Net'], answer: 0 },
  { q: 'Device to connect networks?', options: ['Switch', 'Hub', 'Router', 'Bridge'], answer: 3 },
  { q: 'HTTPS adds…', options: ['Speed', 'Security (TLS)', 'Images', 'Cache'], answer: 1 },
  { q: 'Phishing is…', options: ['Email scam to steal info', 'Fast browsing', 'Network protocol', 'Encrypting files'], answer: 0 },
  { q: 'Strong password includes…', options: ['Common words', 'Only numbers', 'Mix of cases, numbers, symbols', 'Birthdate'], answer: 2 },
  { q: 'Firewall is used to…', options: ['Save power', 'Block unauthorized access', 'Print faster', 'Store files'], answer: 1 },
  { q: 'IP stands for…', options: ['Internet Process', 'Internal Protocol', 'Internet Protocol', 'Interface Port'], answer: 2 },
  { q: '2FA means…', options: ['Two-Factor Auth', 'Two Fast App', 'Trusted File Access', 'None'], answer: 0 },
  { q: 'VPN expands to…', options: ['Virtual Private Network', 'Verified Public Network', 'Virtual Protocol Network', 'None'], answer: 0 },
  { q: 'Malware means…', options: ['Good software', 'Malicious software', 'Mail software', 'Manual ware'], answer: 1 },

  { q: 'SQL used for…', options: ['Styling', 'Database queries', 'Routing', 'Compiling'], answer: 1 },
  { q: 'Primary key is…', options: ['Duplicate field', 'Unique identifier', 'Foreign table', 'Default value'], answer: 1 },
  { q: 'CRUD stands for…', options: ['Create Read Update Delete', 'Copy Run Undo Delete', 'Create Run Use Data', 'None'], answer: 0 },
  { q: 'Which is NoSQL DB?', options: ['MySQL', 'PostgreSQL', 'MongoDB', 'SQLite'], answer: 2 },
  { q: 'REST uses…', options: ['HTTP', 'FTP', 'SMTP', 'SSH'], answer: 0 },
  { q: 'Which is a CSS framework?', options: ['Django', 'Bootstrap', 'Node', 'Express'], answer: 1 },
  { q: 'Responsive design for…', options: ['Performance only', 'Different screen sizes', 'Security', 'Back-end'], answer: 1 },
  { q: 'LocalStorage stores…', options: ['Server data', 'Client key-value pairs', 'Images only', 'Sessions only'], answer: 1 },
  { q: 'What is the first cryptocurrency that used blockchain technology?', options: ['Ethereum', 'Ripple', 'Bitcoin', 'Litecoin'], answer: 2 },
{ q: 'Which consensus mechanism is primarily used by Bitcoin?', options: ['Proof of Work', 'Proof of Stake', 'Delegated Proof of Stake', 'Proof of Authority'], answer: 0 },


  { q: 'Unit of frequency?', options: ['Newton', 'Hertz', 'Watt', 'Ohm'], answer: 1 },
  { q: 'Planet known as Red Planet?', options: ['Mars', 'Jupiter', 'Venus', 'Mercury'], answer: 0 },
  { q: 'Water chemical formula?', options: ['CO2', 'H2O', 'NaCl', 'O2'], answer: 1 },
  { q: 'India’s capital?', options: ['Chennai', 'Mumbai', 'New Delhi', 'Kolkata'], answer: 2 },
  { q: 'Founder of Microsoft?', options: ['Steve Jobs', 'Bill Gates', 'Larry Page', 'Elon Musk'], answer: 1 },
  { q: 'RAM stands for…', options: ['Random Access Memory', 'Read Access Memory', 'Run Access Machine', 'Rapid Access Module'], answer: 0 },
  { q: 'URL stands for…', options: ['Uniform Resource Locator', 'Unified Resource Link', 'Universal Router Link', 'Unique Resource Locator'], answer: 0 },
  { q: 'CPU speed measured in…', options: ['GHz', 'MB', 'ms', 'KB'], answer: 0 },
  { q: 'SSD is faster than…', options: ['HDD', 'RAM', 'CPU', 'GPU'], answer: 0 },
  { q: 'Which language for Android native?', options: ['Kotlin', 'Swift', 'Ruby', 'PHP'], answer: 0 },
];
